---

plugins:
  - import
  - jest
  # - flowtypes

env:
  node: true
  jest: true

parser: babel-eslint

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
  # - 'plugin:flowtypes/recommended'

rules:
  no-console: 0
  